workflows:
  flutter-ios-app:
    name: Flutter iOS App Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        PROJECT_NAME: "MathChallenge"
        BUILD_NUMBER: 1
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          flutter create .
      - name: Build iOS .app
        script: |
          flutter clean
          flutter build ios --release --no-codesign
          mkdir -p build_artifacts
          cp -r build/ios/iphoneos/Runner.app build_artifacts/
    artifacts:
      - build_artifacts/Runner.app
    triggers:
      - push
      - pull_request
